---
title: "GVA + jobs growth data story"
author: "Dan Olner"
date: "2023-10-31"
output: powerpoint_presentation
---

```{r setup, include=FALSE}
#Don't think DPI makes a difference... oh yes it does, ace (not in Word though?)
knitr::opts_chunk$set(echo = F, warning = F, error = F, message = F, comment=NA, fig.width = 17, fig.height = 9)

library(tidyverse)
library(cowplot)
source('../functions/misc_functions.R')
options(scipen = 99)#Avoids scientific notation
```

```{r loaddata}
itl2.cp <- read_csv('../data/sectors/ITL2currentprices_long.csv')

itl2.cp <- itl2.cp %>% 
  split(.$year) %>% 
  map(add_location_quotient_and_proportions, 
      regionvar = ITL_region_name,
      lq_var = SIC07_description,
      valuevar = value) %>% 
  bind_rows()

```



```{r SY_v_UK}
place = 'South Yorkshire'

uk_minus_sy <- itl2.cp$ITL_region_name[!grepl('South Y', itl2.cp$ITL_region_name, ignore.case = T)] %>% unique

#Filter down to just the north

debugonce(twod_proportionplot)
p <- twod_proportionplot(
  df = itl2.cp,
  x_regionnames = place, 
  y_regionnames = uk_minus_sy,
  regionvar = ITL_region_name,
  category_var = SIC07_description, 
  valuevar = value, 
  timevar = year, 
  start_time = 1998,
  # end_time = 2007,
  # start_time = 2008,
  end_time = 2021,
  compasspoints_to_display = c('SW','NW')
  # compasspoints_to_display = c('SE','NE')
)

#add some extras
p <- p + 
  xlab(paste0(place, ' GVA proportion')) +
  ylab(paste0('UK GVA proportion (MINUS ',place,')')) +
  scale_y_log10() +
  scale_x_log10() +
  coord_fixed(xlim = c(0.1,12), ylim = c(0.1,12))# good for log scale
  # coord_fixed(xlim = c(0.1,3), ylim = c(0.1,3))# zoom in

p
```

```{r SY_v_north}
place = 'South Yorkshire'

north <- itl2.cp$ITL_region_name[grepl('Greater Manc|Merseyside|West Y|Cumbria|Cheshire|Lancashire|East Y|North Y|Tees|Northumb|South Y', itl2.cp$ITL_region_name, ignore.case = T)] %>% unique

north_minus_sy <- itl2.cp$ITL_region_name[grepl('Greater Manc|Merseyside|West Y|Cumbria|Cheshire|Lancashire|East Y|North Y|Tees|Northumb|South Y', itl2.cp$ITL_region_name, ignore.case = T)] %>% unique

#Filter down to just the north
p <- twod_proportionplot(
  df = itl2.cp %>% filter(ITL_region_name %in% north),#comparing SY to North only, not the rest of the UK
  x_regionnames = place, 
  y_regionnames = north_minus_sy,
  regionvar = ITL_region_name,
  category_var = SIC07_description, 
  valuevar = value, 
  timevar = year, 
  # start_time = 1998,
  # end_time = 2007,
  start_time = 2008,
  end_time = 2021,
  # compasspoints_to_display = c('SW','NW')
  compasspoints_to_display = c('SE','NE')
)

#add some extras
p <- p + 
  xlab(paste0(place, ' GVA proportion')) +
  ylab(paste0('Northern UK GVA proportion (MINUS ',place,')')) +
  scale_y_log10() +
  scale_x_log10() +
  coord_fixed(xlim = c(0.1,12), ylim = c(0.1,12))# good for log scale
  # coord_fixed(xlim = c(0.1,3), ylim = c(0.1,3))# zoom in

p
```




```{r SY_v_3places_LQplot}
#Use
#LQ_slopes %>% filter(slope==0)
#To see which didn't get slopes (only 8 rows in the current data)
LQ_slopes <- compute_slope_or_zero(
  data = itl2.cp, 
  ITL_region_name, SIC07_description,#slopes will be found within whatever grouping vars are added here
  y = LQ_log, x = year)

#Filter down to a single year
yeartoplot <- itl2.cp %>% filter(year == 2021)

#Add slopes into data to get LQ plots
yeartoplot <- yeartoplot %>% 
  left_join(
    LQ_slopes,
    by = c('ITL_region_name','SIC07_description')
  )

#Get min/max values for LQ over time as well, for each sector and place, to add as bars so range of sector is easy to see
minmaxes <- itl2.cp %>% 
  group_by(SIC07_description,ITL_region_name) %>% 
  summarise(
    min_LQ_all_time = min(LQ),
    max_LQ_all_time = max(LQ)
  )

#Join min and max
yeartoplot <- yeartoplot %>% 
  left_join(
    minmaxes,
    by = c('ITL_region_name','SIC07_description')
  )


place = 'South Yorkshire'

#Get a vector with sectors ordered by the place's LQs, descending order
#Use this next to factor-order the SIC sectors
sectorLQorder <- itl2.cp %>% filter(
  ITL_region_name == place,
  year == 2021,
  LQ < 1
  # LQ > 1
) %>% 
  arrange(-LQ) %>% 
  select(SIC07_description) %>% 
  pull()

#Turn the sector column into a factor and order by LCR's LQs
# yeartoplot$SIC07_description <- factor(yeartoplot$SIC07_description, levels = sectorLQorder, ordered = T)


# Reduce to SY LQ 1+
# lq.selection <- yeartoplot %>% filter(
#   ITL_region_name == place,
#   # slope > 1,#LQ grew relatively over time
#   # LQ > 1
#   LQ < 1
#   )

#Keep only sectors that were LQ > 1 from the main plotting df
yeartoplot <- yeartoplot %>% filter(
  # SIC07_description %in% lq.selection$SIC07_description
  SIC07_description %in% sectorLQorder
)

#Redo factor order just with subset (otherwise can cause problems)
#Might not need the baseplot if doing this. Or, shouldn't actually.
#That was mainly to get factors to behave
yeartoplot$SIC07_description <- factor(yeartoplot$SIC07_description,
                                       levels = sectorLQorder,
                                       ordered = T)


#That's not working. Try ordering by LQ order here

#How has it got a category appearing that's not in the data??
# yeartoplot$SIC07_description[grepl(pattern = 'food',x = yeartoplot$SIC07_description, ignore.case = T)]
# yeartoplot$SIC07_description[grepl(pattern = 'water',x = yeartoplot$SIC07_description, ignore.case = T)]


#Repeat but overlay other places
# debugonce(LQ_baseplot)
p <- LQ_baseplot(df = yeartoplot, alpha = 0, sector_name = SIC07_description, 
                 LQ_column = LQ, change_over_time = slope)

p <- addplacename_to_LQplot(df = yeartoplot, plot_to_addto = p, 
                            placename = 'Greater Manchester', shapenumber = 23,
                            region_name = ITL_region_name,#The next four, the function needs them all 
                            sector_name = SIC07_description, change_over_time = slope, LQ_column = LQ)

p <- addplacename_to_LQplot(df = yeartoplot, plot_to_addto = p, 
                            placename = 'Merseyside', shapenumber = 22,
                            region_name = ITL_region_name,
                            sector_name = SIC07_description, change_over_time = slope, LQ_column = LQ)
 
p <- addplacename_to_LQplot(df = yeartoplot, plot_to_addto = p,
                            placename = 'West Yorkshire', shapenumber = 21,
                            region_name = ITL_region_name,
                            sector_name = SIC07_description, change_over_time = slope, LQ_column = LQ)

p <- addplacename_to_LQplot(df = yeartoplot, plot_to_addto = p, 
                            placename = place, shapenumber = 16,
                            min_LQ_all_time = min_LQ_all_time,max_LQ_all_time = max_LQ_all_time,#Include minmax
                            value_column = value, sector_regional_proportion = sector_regional_proportion,#include numbers
                            region_name = ITL_region_name,
                            sector_name = SIC07_description, change_over_time = slope, LQ_column = LQ)
p <- p + 
  annotate(
    "text",
    label = "South Yorkshire: solid circles\nGreater Manchester: diamonds\nMerseyside: squares\nWest Yorkshire: empty circles",
    x = 0.05, y = sectorLQorder[4],
    
  )

p


```





